# Generated by Django 5.2.5 on 2025-08-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_chapter_number_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.IntegerField(),
        ),
    ]
