# Generated by Django 5.2.5 on 2025-08-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_chapter_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
