# Generated by Django 5.2.5 on 2025-08-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_chapter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
